language: android

android:
  components:
    - platform-tools
    - tools
    - build-tools-26.0.2
    - android-26
    - extra-android-m2repository

jdk:
  - oraclejdk8

env:
  - ANDROID_HOME=$HOME/android-sdk

licenses:
  - 'android-sdk-preview-license-.+'
  - 'android-sdk-license-.+'
  - 'google-gdk-license-.+'

# cache between builds
cache:
  directories:
  - $HOME/.m2
  - $HOME/.gradle

script:
  - ./gradlew --no-daemon --parallel build

before_install:
  - chmod +x gradlew

branches:
  only:
    - master

after_failure: "cat $TRAVIS_BUILD_DIR/app/build/outputs/lint-results-debug.xml"